const tours = [
  {
    id: 'cccc3f63-61c8-4cbd-af6e-fb8b4a469083',
    name: "Art Museum Miami",
    description: "Lorem ipsum Lorem ipsum Lorem ipsum  Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum",
    price: "$50 - $80",
    time: "1 Day",
    destination: 'Miami',
    departureLocation: '2000 Brust St, Detriot, MI 48226, United States',
    startDate: '10/24/2024',
    returnTime: '7:00 PM on Day 3',
    services: ['Basic first aid kit', 'Comfortable Private Booked Transport', ' Fuel Expense', 'Mess Tent, Kitchen Utensils, and Cook', 'Detail Guided Maps', 'Waterproof Tents on twin/triple Sharing'],
    itenerary: [
      { day: 1, temperature: 18, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 2, temperature: 14, forecast: 'cloudy', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 3, temperature: 17, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
    ],
  },
  {
    id: '9e23c3b4-76ee-438c-8515-8301785c9fc0',
    name: "Hard Rock Stadium",
    description: "Lorem ipsum Lorem ipsum Lorem ipsum  Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum",
    price: "$80 - $150",
    time: "1 Day",
    destination: 'Istanbul',
    departureLocation: '2000 Brust St, Detriot, MI 48226, United States',
    startDate: '12/22/2024',
    returnTime: '7:00 PM on Day 3',
    services: ['Basic first aid kit', 'Comfortable Private Booked Transport', ' Fuel Expense', 'Mess Tent, Kitchen Utensils, and Cook', 'Detail Guided Maps', 'Waterproof Tents on twin/triple Sharing'],
    itenerary: [
      { day: 1, temperature: 18, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 2, temperature: 14, forecast: 'cloudy', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 3, temperature: 17, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
    ],
  },
  {
    id: 'd167ed13-70ac-4feb-b22a-96c19fc07425',
    name: "Matheson Hammock Park",
    description: "Lorem ipsum Lorem ipsum Lorem ipsum  Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum",
    price: "$150 - $250",
    time: "2 Days",
    destination: 'Dubai',
    departureLocation: '2000 Brust St, Detriot, MI 48226, United States',
    startDate: '12/28/2024',
    returnTime: '7:00 PM on Day 3',
    services: ['Basic first aid kit', 'Comfortable Private Booked Transport', ' Fuel Expense', 'Mess Tent, Kitchen Utensils, and Cook', 'Detail Guided Maps', 'Waterproof Tents on twin/triple Sharing'],
    itenerary: [
      { day: 1, temperature: 18, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 2, temperature: 14, forecast: 'cloudy', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 3, temperature: 17, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
    ],
  },
  {
    id: '7de09c80-860e-4b75-bb3d-2f2e3aeab79b',
    name: "The Wharf Miami",
    description: "Lorem ipsum Lorem ipsum Lorem ipsum  Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum",
    price: "$300 - $400",
    time: "1 Day",
    destination: 'Chicago',
    departureLocation: '2000 Brust St, Detriot, MI 48226, United States',
    startDate: '12/24/2024',
    returnTime: '7:00 PM on Day 3',
    services: ['Basic first aid kit', 'Comfortable Private Booked Transport', ' Fuel Expense', 'Mess Tent, Kitchen Utensils, and Cook', 'Detail Guided Maps', 'Waterproof Tents on twin/triple Sharing'],
    itenerary: [
      { day: 1, temperature: 18, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 2, temperature: 14, forecast: 'cloudy', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 3, temperature: 17, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
    ],
  },
  {
    id: '7c43181c-3373-48c0-9545-2c78c315f7e6',
    name: "Miami Tower",
    description: "Lorem ipsum Lorem ipsum Lorem ipsum  Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum",
    price: "$350 - $580",
    time: "2 Days",
    destination: 'Dallas',
    departureLocation: '2000 Brust St, Detriot, MI 48226, United States',
    startDate: '12/23/2024',
    returnTime: '7:00 PM on Day 3',
    services: ['Basic first aid kit', 'Comfortable Private Booked Transport', ' Fuel Expense', 'Mess Tent, Kitchen Utensils, and Cook', 'Detail Guided Maps', 'Waterproof Tents on twin/triple Sharing'],
    itenerary: [
      { day: 1, temperature: 18, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 2, temperature: 14, forecast: 'cloudy', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 3, temperature: 17, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
    ],
  },
  {
    id: 'bf1889bb-c2e1-4caf-8b22-e6d67d42419f',
    name: "Skyview Miami",
    description: "Lorem ipsum Lorem ipsum Lorem ipsum  Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum",
    price: "$600 - $800",
    time: "1 Day",
    destination: 'Havaii',
    departureLocation: '2000 Brust St, Detriot, MI 48226, United States',
    startDate: '12/22/2024',
    returnTime: '7:00 PM on Day 3',
    services: ['Basic first aid kit', 'Comfortable Private Booked Transport', ' Fuel Expense', 'Mess Tent, Kitchen Utensils, and Cook', 'Detail Guided Maps', 'Waterproof Tents on twin/triple Sharing'],
    itenerary: [
      { day: 1, temperature: 18, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 2, temperature: 14, forecast: 'cloudy', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 3, temperature: 17, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
    ],
  },
  {
    id: 'a4ccc2e8-26d0-492c-b35e-e9c89f6de25b',
    name: "Santa Cruz",
    description: "Lorem ipsum Lorem ipsum Lorem ipsum  Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum",
    price: "$900 - $1000",
    time: "2 Days",
    destination: 'Berlin',
    departureLocation: '2000 Brust St, Detriot, MI 48226, United States',
    startDate: '12/28/2024',
    returnTime: '7:00 PM on Day 3',
    services: ['Basic first aid kit', 'Comfortable Private Booked Transport', ' Fuel Expense', 'Mess Tent, Kitchen Utensils, and Cook', 'Detail Guided Maps', 'Waterproof Tents on twin/triple Sharing'],
    itenerary: [
      { day: 1, temperature: 18, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 2, temperature: 14, forecast: 'cloudy', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 3, temperature: 17, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
    ],
  },
  {
    id: 'c04d5560-14a1-4e46-9a4e-804e01d6766a',
    name: "Arctic Bay",
    description: "Lorem ipsum Lorem ipsum Lorem ipsum  Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum",
    price: "$1000 - $1300",
    time: "1 Day",
    destination: 'London',
    departureLocation: '2000 Brust St, Detriot, MI 48226, United States',
    startDate: '12/21/2024',
    returnTime: '7:00 PM on Day 3',
    services: ['Basic first aid kit', 'Comfortable Private Booked Transport', ' Fuel Expense', 'Mess Tent, Kitchen Utensils, and Cook', 'Detail Guided Maps', 'Waterproof Tents on twin/triple Sharing'],
    itenerary: [
      { day: 1, temperature: 18, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 2, temperature: 14, forecast: 'cloudy', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 3, temperature: 17, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
    ],
  },
  {
    id: '086cb40e-2d48-4125-a60b-91b579e41011',
    name: "Mandalgobi",
    description: "Lorem ipsum Lorem ipsum Lorem ipsum  Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum",
    price: "$1200 - $1400",
    time: "1 Day",
    destination: 'Ankara',
    departureLocation: '2000 Brust St, Detriot, MI 48226, United States',
    startDate: '12/30/2024',
    returnTime: '7:00 PM on Day 3',
    services: ['Basic first aid kit', 'Comfortable Private Booked Transport', ' Fuel Expense', 'Mess Tent, Kitchen Utensils, and Cook', 'Detail Guided Maps', 'Waterproof Tents on twin/triple Sharing'],
    itenerary: [
      { day: 1, temperature: 18, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 2, temperature: 14, forecast: 'cloudy', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 3, temperature: 17, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
    ],
  },
  {
    id: '3544e208-2ffb-452d-999e-db150889f2e5',
    name: "Erfurt Airport",
    description: "Lorem ipsum Lorem ipsum Lorem ipsum  Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum",
    price: "$230 - $480",
    time: "1 Day",
    destination: 'Orlando',
    departureLocation: '2000 Brust St, Detriot, MI 48226, United States',
    startDate: '12/29/2024',
    returnTime: '7:00 PM on Day 3',
    services: ['Basic first aid kit', 'Comfortable Private Booked Transport', ' Fuel Expense', 'Mess Tent, Kitchen Utensils, and Cook', 'Detail Guided Maps', 'Waterproof Tents on twin/triple Sharing'],
    itenerary: [
      { day: 1, temperature: 18, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 2, temperature: 14, forecast: 'cloudy', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 3, temperature: 17, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
    ],
  },
  {
    id: 'dfcd105c-bda7-4566-9e2c-fd0b7dd9c1bc',
    name: "Kuantan",
    description: "Lorem ipsum Lorem ipsum Lorem ipsum  Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum",
    price: "$150 - $690",
    time: "1 Day",
    destination: 'Cape Town',
    departureLocation: '2000 Brust St, Detriot, MI 48226, United States',
    startDate: '12/24/2024',
    returnTime: '7:00 PM on Day 3',
    services: ['Basic first aid kit', 'Comfortable Private Booked Transport', ' Fuel Expense', 'Mess Tent, Kitchen Utensils, and Cook', 'Detail Guided Maps', 'Waterproof Tents on twin/triple Sharing'],
    itenerary: [
      { day: 1, temperature: 18, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 2, temperature: 14, forecast: 'cloudy', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 3, temperature: 17, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
    ],
  },
  {
    id: '88612013-d74a-4359-bae4-3ea2af38cbb1',
    name: "Budaka",
    description: "Lorem ipsum Lorem ipsum Lorem ipsum  Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum",
    price: "$450 - $600",
    time: "1 Day",
    destination: 'Santorini',
    departureLocation: '2000 Brust St, Detriot, MI 48226, United States',
    startDate: '10/20/2024',
    returnTime: '7:00 PM on Day 3',
    services: ['Basic first aid kit', 'Comfortable Private Booked Transport', ' Fuel Expense', 'Mess Tent, Kitchen Utensils, and Cook', 'Detail Guided Maps', 'Waterproof Tents on twin/triple Sharing'],
    itenerary: [
      { day: 1, temperature: 18, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 2, temperature: 14, forecast: 'cloudy', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 3, temperature: 17, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
    ],
  },
  {
    id: 'bf5c7505-5c90-4d96-8324-9d5dc1a56005',
    name: "Usagara",
    description: "Lorem ipsum Lorem ipsum Lorem ipsum  Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum",
    price: "$1100 - $1200",
    time: "1 Day",
    destination: 'Madrid',
    departureLocation: '2000 Brust St, Detriot, MI 48226, United States',
    startDate: '11/29/2024',
    returnTime: '7:00 PM on Day 3',
    services: ['Basic first aid kit', 'Comfortable Private Booked Transport', ' Fuel Expense', 'Mess Tent, Kitchen Utensils, and Cook', 'Detail Guided Maps', 'Waterproof Tents on twin/triple Sharing'],
    itenerary: [
      { day: 1, temperature: 18, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 2, temperature: 14, forecast: 'cloudy', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 3, temperature: 17, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
    ],
  },
  {
    id: 'c7fce15f-2e11-4e93-b8b7-ef4568548a85',
    name: "Datarsitu",
    description: "Lorem ipsum Lorem ipsum Lorem ipsum  Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum",
    price: "$500 - $550",
    time: "1 Day",
    destination: 'New Orleans',
    departureLocation: '2000 Brust St, Detriot, MI 48226, United States',
    startDate: '12/29/2024',
    returnTime: '7:00 PM on Day 3',
    services: ['Basic first aid kit', 'Comfortable Private Booked Transport', ' Fuel Expense', 'Mess Tent, Kitchen Utensils, and Cook', 'Detail Guided Maps', 'Waterproof Tents on twin/triple Sharing'],
    itenerary: [
      { day: 1, temperature: 18, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 2, temperature: 14, forecast: 'cloudy', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
      { day: 3, temperature: 17, forecast: 'sunny', items: ['Tours with American Sign Language', 'Audio description group tours', 'Large-print gallery notes', 'Lunch included.'] },
    ],
  },
];

module.exports = tours;
